import "@styles/global.css";
import Header from "@/components/Header/Header";
import Footer from '@components/Footer/Footer';
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({children}) => {
  return (
    <html lang="en">
      <body>
        <Providers>
            <Header />
            {children}
            <Footer />
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout